/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
* Class           VeryVeryBoards
* File            VeryVeryBoards.java
* Description     A program used to rent snowboards to enjoy your time 
*                 snowboarding on the wonderful hills of Iceland.
*                 
*                 Prices are:
*                 Snowboards = $40.00
*                 Snowboards w/boots = $65.00

* @author         <i>Toufic Majdalani</i>
* Environment     PC, Windows 10, NetBeans IDE 8.2, jdk 1.8.0_131
* Date            1/30/2020
* @version        1.0.0
* @see            javax.swing.JOptionPane
* @see            javax.swing.JFrame
*</pre>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
package Project1;

import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;



public class VeryVeryBoards extends javax.swing.JFrame 
{
    int snowboardsTotalQuantity = 0,snowboardsBootsTotalQuantity = 0;
            
            
    double grandRentTotal = 0, avgChargeCust = 0;
    int counter = 0;
    
    

    /**
     * Creates new form VeryVeryBoards
     */
    public VeryVeryBoards() {
        initComponents();
        this.getRootPane().setDefaultButton(calculateJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Project1/snowboarding_icon.jpg"));
        //center the form
        this.setLocationRelativeTo(this);
        //sets date format on panel
        setDate();
        //set JSpinner to become non-editable
        JFormattedTextField tfSnow =
                ((JSpinner.DefaultEditor)snowboardsJSpinner.getEditor
                ()).getTextField();tfSnow.setEditable(false);
        JFormattedTextField tfBoots =
                ((JSpinner.DefaultEditor)snowboardsJSpinner.getEditor
                ()).getTextField();tfBoots.setEditable(false);
    }
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          setDate()
    *	Description     Calls DateFormat class for JPanel
    *	@author         <i>Toufic Majdalani</i>
    *   @param          dateFormat()
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void setDate()
    {
     DateFormat dateFormat = new SimpleDateFormat("EEEE, MMMMMM dd, yyyy   "
             + "HH:mm:ss");
     Date now = new Date();
//     dailyrentalsummaryJPanel.setBorder(BorderFactory.createTitledBorder("Daily Rental Summary " + dateFormat.format(now)));
     dailyRentJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
             null, "Daily Rental Summary " 
             + dateFormat.format(now), 
             javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
             javax.swing.border.TitledBorder.DEFAULT_POSITION, 
             new java.awt.Font("Tahoma", 2, 12), 
             new java.awt.Color(0, 153, 0))); 
     this.setTitle("Very Very Boards-- " + dateFormat.format(now));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberofboardsJPanel = new javax.swing.JPanel();
        customerNameJLabel = new javax.swing.JLabel();
        customerIDJLabel = new javax.swing.JLabel();
        snowboardsJLabel = new javax.swing.JLabel();
        snowboardsBootsJLabel = new javax.swing.JLabel();
        customerNameJTextField = new javax.swing.JTextField();
        customerIDJFormattedTextField = new javax.swing.JFormattedTextField();
        snowboardsJSpinner = new javax.swing.JSpinner();
        snowboardsBootsJSpinner = new javax.swing.JSpinner();
        customerRentSummaryJPanel = new javax.swing.JPanel();
        snowboardsTotalJLabel = new javax.swing.JLabel();
        snowboardsBootsTotalJLabel = new javax.swing.JLabel();
        rentalTotalJLabel = new javax.swing.JLabel();
        snowboardsTotalJTextField = new javax.swing.JTextField();
        snowboardsBootsTotalJTextField = new javax.swing.JTextField();
        rentalTotalJTextField = new javax.swing.JTextField();
        dailyRentJPanel = new javax.swing.JPanel();
        snowboardsGTotalJLabel = new javax.swing.JLabel();
        snowboardsBootsGTotalJLabel = new javax.swing.JLabel();
        rentalgrandtotalJLabel = new javax.swing.JLabel();
        snowboardsGTotalJTextField = new javax.swing.JTextField();
        snowboardsBootsGTotalJTextField = new javax.swing.JTextField();
        grandRentalTotalJTextField = new javax.swing.JTextField();
        avgChargeJLabel = new javax.swing.JLabel();
        avgChargeJTextField = new javax.swing.JTextField();
        buttonsJPanel = new javax.swing.JPanel();
        calculateJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        clearAllJButton = new javax.swing.JButton();
        snowboardingICOJLabel = new javax.swing.JLabel();
        boardsJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        clearAllJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Very Very Boards");
        setResizable(false);

        numberofboardsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Boards Rented", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        customerNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerNameJLabel.setText("Customer Name");

        customerIDJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerIDJLabel.setText("Customer ID");

        snowboardsJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsJLabel.setText("Snowboards");

        snowboardsBootsJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsBootsJLabel.setText("Snowboards w/ boots");

        customerNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerNameJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        try {
            customerIDJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        customerIDJFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        snowboardsJSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        snowboardsBootsJSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsBootsJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout numberofboardsJPanelLayout = new javax.swing.GroupLayout(numberofboardsJPanel);
        numberofboardsJPanel.setLayout(numberofboardsJPanelLayout);
        numberofboardsJPanelLayout.setHorizontalGroup(
            numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberofboardsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numberofboardsJPanelLayout.createSequentialGroup()
                        .addComponent(snowboardsBootsJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snowboardsBootsJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(numberofboardsJPanelLayout.createSequentialGroup()
                        .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameJLabel)
                            .addComponent(customerIDJLabel)
                            .addComponent(snowboardsJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snowboardsJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        numberofboardsJPanelLayout.setVerticalGroup(
            numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberofboardsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameJLabel)
                    .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDJLabel)
                    .addComponent(customerIDJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsJLabel)
                    .addComponent(snowboardsJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(numberofboardsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsBootsJLabel)
                    .addComponent(snowboardsBootsJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        customerRentSummaryJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Rental Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        snowboardsTotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsTotalJLabel.setText("Snowboards");

        snowboardsBootsTotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsBootsTotalJLabel.setText("Snowboards w/ boots");

        rentalTotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rentalTotalJLabel.setText("Rental Total");

        snowboardsTotalJTextField.setEditable(false);
        snowboardsTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        snowboardsTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        snowboardsTotalJTextField.setText("$0.00");

        snowboardsBootsTotalJTextField.setEditable(false);
        snowboardsBootsTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        snowboardsBootsTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsBootsTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        snowboardsBootsTotalJTextField.setText("$0.00");

        rentalTotalJTextField.setEditable(false);
        rentalTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        rentalTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rentalTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rentalTotalJTextField.setText("$0.00");

        javax.swing.GroupLayout customerRentSummaryJPanelLayout = new javax.swing.GroupLayout(customerRentSummaryJPanel);
        customerRentSummaryJPanel.setLayout(customerRentSummaryJPanelLayout);
        customerRentSummaryJPanelLayout.setHorizontalGroup(
            customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerRentSummaryJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snowboardsBootsTotalJLabel)
                    .addComponent(snowboardsTotalJLabel)
                    .addComponent(rentalTotalJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentalTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(snowboardsTotalJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(snowboardsBootsTotalJTextField)))
                .addGap(46, 46, 46))
        );
        customerRentSummaryJPanelLayout.setVerticalGroup(
            customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerRentSummaryJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsTotalJLabel)
                    .addComponent(snowboardsTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsBootsTotalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snowboardsBootsTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(customerRentSummaryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalTotalJLabel)
                    .addComponent(rentalTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        dailyRentJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daily Rental Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        snowboardsGTotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsGTotalJLabel.setText("Snowboards");

        snowboardsBootsGTotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        snowboardsBootsGTotalJLabel.setText("Snowboards w/ boots");

        rentalgrandtotalJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rentalgrandtotalJLabel.setText("Total rental charges");

        snowboardsGTotalJTextField.setEditable(false);
        snowboardsGTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        snowboardsGTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsGTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        snowboardsGTotalJTextField.setText("0");

        snowboardsBootsGTotalJTextField.setEditable(false);
        snowboardsBootsGTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        snowboardsBootsGTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        snowboardsBootsGTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        snowboardsBootsGTotalJTextField.setText("0");

        grandRentalTotalJTextField.setEditable(false);
        grandRentalTotalJTextField.setBackground(new java.awt.Color(204, 204, 204));
        grandRentalTotalJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grandRentalTotalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        grandRentalTotalJTextField.setText("$0.00");

        avgChargeJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avgChargeJLabel.setText("Average charge/cust.");

        avgChargeJTextField.setEditable(false);
        avgChargeJTextField.setBackground(new java.awt.Color(204, 204, 204));
        avgChargeJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        avgChargeJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        avgChargeJTextField.setText("$0.00");

        javax.swing.GroupLayout dailyRentJPanelLayout = new javax.swing.GroupLayout(dailyRentJPanel);
        dailyRentJPanel.setLayout(dailyRentJPanelLayout);
        dailyRentJPanelLayout.setHorizontalGroup(
            dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyRentJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avgChargeJLabel)
                    .addComponent(snowboardsBootsGTotalJLabel)
                    .addComponent(snowboardsGTotalJLabel)
                    .addComponent(rentalgrandtotalJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grandRentalTotalJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgChargeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snowboardsGTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snowboardsBootsGTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        dailyRentJPanelLayout.setVerticalGroup(
            dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyRentJPanelLayout.createSequentialGroup()
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsGTotalJLabel)
                    .addComponent(snowboardsGTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snowboardsBootsGTotalJLabel)
                    .addComponent(snowboardsBootsGTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalgrandtotalJLabel)
                    .addComponent(grandRentalTotalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dailyRentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgChargeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgChargeJLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        buttonsJPanel.setLayout(new java.awt.GridLayout(2, 4, 3, 3));

        calculateJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        calculateJButton.setMnemonic('c');
        calculateJButton.setText("Calculate");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(calculateJButton);

        quitJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        quitJButton.setMnemonic('q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(quitJButton);

        clearJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clearJButton.setMnemonic('l');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(clearJButton);

        clearAllJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clearAllJButton.setMnemonic('a');
        clearAllJButton.setText("Clear All");
        clearAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(clearAllJButton);

        snowboardingICOJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snowboardingICOJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/snowboarding_icon.jpg"))); // NOI18N

        fileJMenu.setMnemonic('f');
        fileJMenu.setText("File");
        fileJMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        clearJMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearJMenuItem.setMnemonic('c');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        clearAllJMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearAllJMenuItem.setMnemonic('l');
        clearAllJMenuItem.setText("Clear all");
        clearAllJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearAllJMenuItem);

        printJMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printJMenuItem.setMnemonic('p');
        printJMenuItem.setText("Print");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);

        quitJMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quitJMenuItem.setMnemonic('q');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(quitJMenuItem);

        boardsJMenuBar.add(fileJMenu);

        helpJMenu.setMnemonic('h');
        helpJMenu.setText("Help");
        helpJMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        aboutJMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aboutJMenuItem.setMnemonic('a');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        boardsJMenuBar.add(helpJMenu);

        setJMenuBar(boardsJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberofboardsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerRentSummaryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(snowboardingICOJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dailyRentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberofboardsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyRentJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonsJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerRentSummaryJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(snowboardingICOJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          clearJMenuItemActionPerformed()
    *	Description     Calls clearJButton and clears textboxes and spinners
    *                   in first and second panel.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        clearJButtonActionPerformed(evt);
    }//GEN-LAST:event_clearJMenuItemActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          quitJButtonActionPerformed()
    *	Description     Closes the form!
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
      System.exit(0); //closes form
    }//GEN-LAST:event_quitJButtonActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          quitJMenuItemActionPerformed()
    *	Description     Calls quitJButton and closes form
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        quitJButtonActionPerformed(evt); //call button event handler
    }//GEN-LAST:event_quitJMenuItemActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          clearJButtonActionPerformed()
    *	Description     Clears textboxes and spinners in first and second
    *                   panel.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        //clear textboxes in first and second panel
        customerNameJTextField.setText("");
        customerIDJFormattedTextField.setText("");
        //resets spinners to 0
        snowboardsJSpinner.setValue(0);
        snowboardsBootsJSpinner.setValue(0);
        //clear rest of textboxes
        snowboardsTotalJTextField.setText("$0.00");
        snowboardsBootsTotalJTextField.setText("$0.00");
        rentalTotalJTextField.setText("$0.00");
        //set focus on customer name textbox
        customerNameJTextField.requestFocus();
    }//GEN-LAST:event_clearJButtonActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          clearAllJButtonActionPerformed()
    *	Description     Clears all the textboxes and spinners in the form.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllJButtonActionPerformed
        //clear textboxes in first and second panel
        customerNameJTextField.setText("");
        customerIDJFormattedTextField.setText("");
        //resets spinners to 0
        snowboardsJSpinner.setValue(0);
        snowboardsBootsJSpinner.setValue(0);
        //clear rest of textboxes
        snowboardsTotalJTextField.setText("$0.00");
        snowboardsBootsTotalJTextField.setText("$0.00");
        rentalTotalJTextField.setText("$0.00");
        snowboardsGTotalJTextField.setText("0");
        snowboardsBootsGTotalJTextField.setText("0");
        grandRentalTotalJTextField.setText("$0.00");
        avgChargeJTextField.setText("$0.00");
        //set focus on customer name textbox
        customerNameJTextField.requestFocus();
        grandRentTotal = 0;
        avgChargeCust = 0;
        counter = 0;
        snowboardsTotalQuantity = 0; 
        snowboardsBootsTotalQuantity = 0;
        
    }//GEN-LAST:event_clearAllJButtonActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          clearAllJMenuItemActionPerformed()
    *	Description     Calls clearAllJButton and clears all textboxes and
    *                   spinners.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearAllJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllJMenuItemActionPerformed
        clearAllJButtonActionPerformed(evt);
    }//GEN-LAST:event_clearAllJMenuItemActionPerformed
 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          calculateJButtonActionPerformed()
    *	Description     Calculates the rental total of snowboards with or
    *                   without boots with running total of daily rentals of 
    *                   boards.
    * 
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *   @see            java.text.DecimalFormat
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Class           dollars()
    *	Description     Defines a decimal format class with a currency $ sign
    *                   on it.
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        ++counter;
        //step 1: declaration of variables and constants
        
        DecimalFormat dollars = new DecimalFormat("$#,###,##0.00");
        final int SNOWBOARDS_PLAIN = 40, SNOWBOARDS_BOOTS = 65;
        int snowboards, snowboardsBoots, ID = 0; 
        double snowboardsTotal, snowboardsBootsTotal, rentalTotal;
        
        //step 2: inputs
        snowboards = Integer.parseInt(snowboardsJSpinner.getValue().toString());
        
        snowboardsBoots = Integer.parseInt
        (snowboardsBootsJSpinner.getValue().toString());
        
        
        
        //step 3: calculations
        snowboardsTotal = SNOWBOARDS_PLAIN * snowboards;
        snowboardsBootsTotal = SNOWBOARDS_BOOTS * snowboardsBoots;
        rentalTotal = snowboardsTotal + snowboardsBootsTotal;
        snowboardsTotalQuantity = snowboards + snowboardsTotalQuantity;
        snowboardsBootsTotalQuantity = snowboardsBootsTotalQuantity + snowboardsBoots;
        grandRentTotal = grandRentTotal + rentalTotal;
        avgChargeCust = grandRentTotal / counter;
        
        //step 4: outputs
        snowboardsTotalJTextField.setText(dollars.format(snowboardsTotal));
        snowboardsBootsTotalJTextField.setText(dollars.format(snowboardsBootsTotal));
        rentalTotalJTextField.setText(dollars.format(rentalTotal));
        snowboardsGTotalJTextField.setText(String.valueOf(snowboardsTotalQuantity));
        snowboardsBootsGTotalJTextField.setText(String.valueOf(snowboardsBootsTotalQuantity));
        grandRentalTotalJTextField.setText(String.valueOf(dollars.format(grandRentTotal)));
        avgChargeJTextField.setText(String.valueOf(dollars.format(avgChargeCust)));
        
        
    }//GEN-LAST:event_calculateJButtonActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          printJMenuItemActionPerformed()
    *	Description     Prints form in GUI.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJMenuItemActionPerformed
      PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJMenuItemActionPerformed
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method          aboutJMenuItemActionPerformed()
    *	Description     Opens help and about forum for GUI.
    *	@param          evt java.awt.event.ActionEvent
    *   @see            java.awt.event.ActionEvent
    *	@author         <i>Toufic Majdalani</i>
    *	Date            1/30/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        About myAbout = new About(this, false);
        myAbout.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        main()
    * Description   Calls default constructor for VeryVeryBoards
    * @param        args String []
    * @author       <i>Toufic Majdalani</i>
    * Date          1/23/2020
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeryVeryBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeryVeryBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeryVeryBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeryVeryBoards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeryVeryBoards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JLabel avgChargeJLabel;
    private javax.swing.JTextField avgChargeJTextField;
    private javax.swing.JMenuBar boardsJMenuBar;
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearAllJButton;
    private javax.swing.JMenuItem clearAllJMenuItem;
    private javax.swing.JButton clearJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JFormattedTextField customerIDJFormattedTextField;
    private javax.swing.JLabel customerIDJLabel;
    private javax.swing.JLabel customerNameJLabel;
    private javax.swing.JTextField customerNameJTextField;
    private javax.swing.JPanel customerRentSummaryJPanel;
    private javax.swing.JPanel dailyRentJPanel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JTextField grandRentalTotalJTextField;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JPanel numberofboardsJPanel;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JLabel rentalTotalJLabel;
    private javax.swing.JTextField rentalTotalJTextField;
    private javax.swing.JLabel rentalgrandtotalJLabel;
    private javax.swing.JLabel snowboardingICOJLabel;
    private javax.swing.JLabel snowboardsBootsGTotalJLabel;
    private javax.swing.JTextField snowboardsBootsGTotalJTextField;
    private javax.swing.JLabel snowboardsBootsJLabel;
    private javax.swing.JSpinner snowboardsBootsJSpinner;
    private javax.swing.JLabel snowboardsBootsTotalJLabel;
    private javax.swing.JTextField snowboardsBootsTotalJTextField;
    private javax.swing.JLabel snowboardsGTotalJLabel;
    private javax.swing.JTextField snowboardsGTotalJTextField;
    private javax.swing.JLabel snowboardsJLabel;
    private javax.swing.JSpinner snowboardsJSpinner;
    private javax.swing.JLabel snowboardsTotalJLabel;
    private javax.swing.JTextField snowboardsTotalJTextField;
    // End of variables declaration//GEN-END:variables
}
